/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_api_v1_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Expenses */
        get: operations["get_expenses_api_v1_expenses_get"];
        put?: never;
        /** Post Expense */
        post: operations["post_expense_api_v1_expenses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses/extract-receipt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Extract Receipt
         * @description Propose receipt lines from an image; the server recomputes totals before answering.
         */
        post: operations["post_extract_receipt_api_v1_expenses_extract_receipt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses/jev-chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Jev Chat
         * @description Árbitro Jev: correct a receipt extraction in natural language; nothing is persisted.
         */
        post: operations["post_jev_chat_api_v1_expenses_jev_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses/review-batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Expense Batch Review */
        post: operations["post_expense_batch_review_api_v1_expenses_review_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses/{expense_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Expense */
        patch: operations["patch_expense_api_v1_expenses__expense_id__patch"];
        trace?: never;
    };
    "/api/v1/expenses/{expense_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Expense Cancel */
        post: operations["post_expense_cancel_api_v1_expenses__expense_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses/{expense_id}/receipt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Expense Receipt */
        patch: operations["patch_expense_receipt_api_v1_expenses__expense_id__receipt_patch"];
        trace?: never;
    };
    "/api/v1/expenses/{expense_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Expense Review */
        post: operations["post_expense_review_api_v1_expenses__expense_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Health */
        get: operations["api_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hermes/hmac-probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hmac Probe */
        post: operations["hmac_probe_api_v1_hermes_hmac_probe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hermes/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hermes Tools */
        get: operations["hermes_tools_api_v1_hermes_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hermes/tools/{tool_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invoke Hermes Tool */
        post: operations["invoke_hermes_tool_api_v1_hermes_tools__tool_name__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Incomes */
        get: operations["get_incomes_api_v1_incomes_get"];
        put?: never;
        /** Post Income */
        post: operations["post_income_api_v1_incomes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/neodata/imports/{import_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Neodata Import */
        post: operations["confirm_neodata_import_api_v1_neodata_imports__import_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/neodata/imports/{import_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Neodata Preview */
        patch: operations["patch_neodata_preview_api_v1_neodata_imports__import_id__preview_patch"];
        trace?: never;
    };
    "/api/v1/neodata/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Neodata */
        post: operations["preview_neodata_api_v1_neodata_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/works/{work_id}.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Work Pdf */
        get: operations["export_work_pdf_api_v1_reports_works__work_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/works/{work_id}.xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Work Excel */
        get: operations["export_work_excel_api_v1_reports_works__work_id__xlsx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subcontracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Subcontracts */
        get: operations["get_subcontracts_api_v1_subcontracts_get"];
        put?: never;
        /** Post Subcontract */
        post: operations["post_subcontract_api_v1_subcontracts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subcontracts/{subcontract_id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Subcontract Payment */
        post: operations["post_subcontract_payment_api_v1_subcontracts__subcontract_id__payments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/supplier-specialties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Supplier Specialties */
        get: operations["get_supplier_specialties_api_v1_supplier_specialties_get"];
        put?: never;
        /** Post Supplier Specialty */
        post: operations["post_supplier_specialty_api_v1_supplier_specialties_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/supplier-specialties/{specialty_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Supplier Specialty */
        patch: operations["patch_supplier_specialty_api_v1_supplier_specialties__specialty_id__patch"];
        trace?: never;
    };
    "/api/v1/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Suppliers */
        get: operations["get_suppliers_api_v1_suppliers_get"];
        put?: never;
        /** Post Supplier */
        post: operations["post_supplier_api_v1_suppliers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppliers/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Supplier Analytics */
        get: operations["get_supplier_analytics_api_v1_suppliers_analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppliers/extract-csf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Extract Csf
         * @description Propose supplier fiscal data from a CSF; nothing is persisted besides tool_call_log.
         */
        post: operations["post_extract_csf_api_v1_suppliers_extract_csf_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppliers/{supplier_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Supplier Detail */
        get: operations["get_supplier_detail_api_v1_suppliers__supplier_id__get"];
        put?: never;
        post?: never;
        /** Delete Supplier */
        delete: operations["delete_supplier_api_v1_suppliers__supplier_id__delete"];
        options?: never;
        head?: never;
        /** Patch Supplier */
        patch: operations["patch_supplier_api_v1_suppliers__supplier_id__patch"];
        trace?: never;
    };
    "/api/v1/suppliers/{supplier_id}/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Supplier Evaluation */
        post: operations["post_supplier_evaluation_api_v1_suppliers__supplier_id__evaluations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppliers/{supplier_id}/evaluations/{evaluation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Supplier Evaluation */
        delete: operations["delete_supplier_evaluation_api_v1_suppliers__supplier_id__evaluations__evaluation_id__delete"];
        options?: never;
        head?: never;
        /** Patch Supplier Evaluation */
        patch: operations["patch_supplier_evaluation_api_v1_suppliers__supplier_id__evaluations__evaluation_id__patch"];
        trace?: never;
    };
    "/api/v1/suppliers/{supplier_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Supplier Restore */
        post: operations["post_supplier_restore_api_v1_suppliers__supplier_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppliers/{supplier_id}/works/{work_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Supplier Work */
        put: operations["put_supplier_work_api_v1_suppliers__supplier_id__works__work_id__put"];
        post?: never;
        /** Delete Supplier Work */
        delete: operations["delete_supplier_work_api_v1_suppliers__supplier_id__works__work_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/weekly-closes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Weekly Close */
        post: operations["post_weekly_close_api_v1_weekly_closes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/weekly-closes/{close_id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Weekly Reopen */
        post: operations["post_weekly_reopen_api_v1_weekly_closes__close_id__reopen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/works": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Works */
        get: operations["get_works_api_v1_works_get"];
        put?: never;
        /** Post Work */
        post: operations["post_work_api_v1_works_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/works/{work_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Work Detail */
        get: operations["get_work_detail_api_v1_works__work_id__get"];
        put?: never;
        post?: never;
        /** Remove Work */
        delete: operations["remove_work_api_v1_works__work_id__delete"];
        options?: never;
        head?: never;
        /** Patch Work */
        patch: operations["patch_work_api_v1_works__work_id__patch"];
        trace?: never;
    };
    "/api/v1/works/{work_id}/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Work Catalog */
        get: operations["get_work_catalog_api_v1_works__work_id__catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/works/{work_id}/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Work Expenses */
        get: operations["get_work_expenses_api_v1_works__work_id__expenses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/works/{work_id}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Work Overview */
        get: operations["get_work_overview_api_v1_works__work_id__overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/works/{work_id}/weekly-closes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Weekly Closes */
        get: operations["get_weekly_closes_api_v1_works__work_id__weekly_closes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/works/{work_id}/weekly-closes/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Weekly Close Preview */
        get: operations["get_weekly_close_preview_api_v1_works__work_id__weekly_closes_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_post_extract_csf_api_v1_suppliers_extract_csf_post */
        Body_post_extract_csf_api_v1_suppliers_extract_csf_post: {
            /**
             * File
             * Format: binary
             * @description Constancia de Situación Fiscal del SAT (PDF)
             */
            file: string;
        };
        /** Body_post_extract_receipt_api_v1_expenses_extract_receipt_post */
        Body_post_extract_receipt_api_v1_expenses_extract_receipt_post: {
            /**
             * File
             * Format: binary
             * @description Foto del ticket o nota de remisión
             */
            file: string;
        };
        /** Body_preview_neodata_api_v1_neodata_preview_post */
        Body_preview_neodata_api_v1_neodata_preview_post: {
            /**
             * File
             * Format: binary
             * @description Libro .xlsx exportado por NEODATA
             */
            file: string;
            /** Import Type */
            import_type: string;
            /** Work End Date */
            work_end_date?: string | null;
            /** Work Id */
            work_id?: string | null;
            /** Work Location */
            work_location?: string | null;
            /** Work Name */
            work_name?: string | null;
            /** Work Start Date */
            work_start_date?: string | null;
        };
        /** CsfExtraction */
        CsfExtraction: {
            /** Codigo Postal */
            codigo_postal: string | null;
            /** Motivos Revision */
            motivos_revision: string[];
            /** Razon Social */
            razon_social: string | null;
            /** Regimen Fiscal */
            regimen_fiscal: string | null;
            /** Requiere Validacion Humana */
            requiere_validacion_humana: boolean;
            /** Rfc */
            rfc: string | null;
        };
        /** CsfExtractionResponse */
        CsfExtractionResponse: {
            extraction: components["schemas"]["CsfExtraction"];
            /** Model */
            model: string | null;
            /**
             * Tool Call Log Id
             * Format: uuid
             */
            tool_call_log_id: string;
        };
        /** ExpenseBatchReview */
        ExpenseBatchReview: {
            /** Expense Ids */
            expense_ids: string[];
            /**
             * Work Id
             * Format: uuid
             */
            work_id: string;
        };
        /** ExpenseCancel */
        ExpenseCancel: {
            /** Reason */
            reason: string;
        };
        /** ExpenseCreate */
        ExpenseCreate: {
            /** Amount */
            amount: number | string;
            /**
             * Area Id
             * Format: uuid
             */
            area_id: string;
            /** Budget Item Id */
            budget_item_id?: string | null;
            /** Concept */
            concept: string;
            /**
             * Expense Category Id
             * Format: uuid
             */
            expense_category_id: string;
            /**
             * Expense Item Id
             * Format: uuid
             */
            expense_item_id: string;
            /**
             * Expense Subitem Id
             * Format: uuid
             */
            expense_subitem_id: string;
            /** Folio */
            folio?: string | null;
            /**
             * Spent On
             * Format: date
             */
            spent_on: string;
            /** @default pendiente */
            state: components["schemas"]["ExpenseState"];
            /**
             * Supplier Id
             * Format: uuid
             */
            supplier_id: string;
            /**
             * Work Id
             * Format: uuid
             */
            work_id: string;
        };
        /** ExpenseReview */
        ExpenseReview: {
            /** Action */
            action: string;
            /** Reason */
            reason?: string | null;
        };
        /**
         * ExpenseState
         * @enum {string}
         */
        ExpenseState: "pendiente" | "validado" | "rechazado";
        /** ExpenseUpdate */
        ExpenseUpdate: {
            /** Amount */
            amount: number | string;
            /**
             * Area Id
             * Format: uuid
             */
            area_id: string;
            /** Budget Item Id */
            budget_item_id?: string | null;
            /** Concept */
            concept: string;
            /**
             * Expense Category Id
             * Format: uuid
             */
            expense_category_id: string;
            /**
             * Expense Item Id
             * Format: uuid
             */
            expense_item_id: string;
            /**
             * Expense Subitem Id
             * Format: uuid
             */
            expense_subitem_id: string;
            /** Folio */
            folio?: string | null;
            /**
             * Spent On
             * Format: date
             */
            spent_on: string;
            /**
             * Supplier Id
             * Format: uuid
             */
            supplier_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Service */
            service: string;
            /** Status */
            status: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Version */
            version: string;
        };
        /** ImportConfirm */
        ImportConfirm: {
            /** Confirmation */
            confirmation: boolean;
        };
        /** ImportPreviewUpdate */
        ImportPreviewUpdate: {
            /** Items */
            items: components["schemas"]["PreviewItemCorrection"][];
        };
        /** IncomeCreate */
        IncomeCreate: {
            /** Actual Date */
            actual_date?: string | null;
            /** Amount */
            amount: number | string;
            /** Concept */
            concept: string;
            /**
             * Estimated Date
             * Format: date
             */
            estimated_date: string;
            /** State */
            state: string;
            /**
             * Work Id
             * Format: uuid
             */
            work_id: string;
        };
        /** JevChatRequest */
        JevChatRequest: {
            extraction: components["schemas"]["ReceiptExtraction-Input"];
            /** Instruction */
            instruction: string;
        };
        /** JevChatResponse */
        JevChatResponse: {
            extraction: components["schemas"]["ReceiptExtraction-Output"];
            /** Model */
            model: string | null;
            /** Respuesta */
            respuesta: string;
            /**
             * Tool Call Log Id
             * Format: uuid
             */
            tool_call_log_id: string;
        };
        /** PreviewItemCorrection */
        PreviewItemCorrection: {
            /** Area */
            area: string;
            /** Category */
            category?: string | null;
            /** Code */
            code: string;
            /** Description */
            description: string;
            /** Row */
            row: number;
            /** Sheet */
            sheet: string;
            /** Unit */
            unit: string;
            /** Work Class */
            work_class: string;
        };
        /** ReceiptConcept */
        "ReceiptConcept-Input": {
            /** Cantidad */
            cantidad: number | string | null;
            /** Descripcion */
            descripcion: string | null;
            /** Precio Unitario */
            precio_unitario: number | string | null;
        };
        /** ReceiptConcept */
        "ReceiptConcept-Output": {
            /** Cantidad */
            cantidad: string | null;
            /** Descripcion */
            descripcion: string | null;
            /** Precio Unitario */
            precio_unitario: string | null;
        };
        /** ReceiptExtraction */
        "ReceiptExtraction-Input": {
            /** Conceptos */
            conceptos: components["schemas"]["ReceiptConcept-Input"][];
            /** Motivos Revision */
            motivos_revision: string[];
            /** Requiere Validacion Humana */
            requiere_validacion_humana: boolean;
            /** Suma Conceptos */
            suma_conceptos: number | string | null;
            /** Total Detectado */
            total_detectado: number | string | null;
        };
        /** ReceiptExtraction */
        "ReceiptExtraction-Output": {
            /** Conceptos */
            conceptos: components["schemas"]["ReceiptConcept-Output"][];
            /** Motivos Revision */
            motivos_revision: string[];
            /** Requiere Validacion Humana */
            requiere_validacion_humana: boolean;
            /** Suma Conceptos */
            suma_conceptos: string | null;
            /** Total Detectado */
            total_detectado: string | null;
        };
        /** ReceiptExtractionResponse */
        ReceiptExtractionResponse: {
            extraction: components["schemas"]["ReceiptExtraction-Output"];
            /** Model */
            model: string | null;
            /**
             * Tool Call Log Id
             * Format: uuid
             */
            tool_call_log_id: string;
        };
        /** ReceiptUpdate */
        ReceiptUpdate: {
            /** Path */
            path: string;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "admin" | "operativo";
        /** SubcontractCreate */
        SubcontractCreate: {
            /** Concept */
            concept: string;
            /** Contracted Amount */
            contracted_amount: number | string;
            /** Scope */
            scope?: string | null;
            /** Subcontractor */
            subcontractor: string;
            /**
             * Work Id
             * Format: uuid
             */
            work_id: string;
        };
        /** SubcontractPaymentCreate */
        SubcontractPaymentCreate: {
            /** Amount */
            amount: number | string;
            /** Linked Expense Id */
            linked_expense_id?: string | null;
            /**
             * Spent On
             * Format: date
             */
            spent_on: string;
        };
        /** SupplierArchive */
        SupplierArchive: {
            /** Reason */
            reason: string;
        };
        /** SupplierCreate */
        SupplierCreate: {
            /** Address */
            address?: string | null;
            /** Contact Name */
            contact_name?: string | null;
            /** Coverage */
            coverage?: string | null;
            /** Email */
            email?: string | null;
            /** Legal Name */
            legal_name?: string | null;
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /** Phone */
            phone?: string | null;
            /** Postal Code */
            postal_code?: string | null;
            /** Specialty Ids */
            specialty_ids?: string[];
            /** Tax Id */
            tax_id?: string | null;
            /** Tax Regime */
            tax_regime?: string | null;
            /** Whatsapp */
            whatsapp?: string | null;
        };
        /** SupplierEvaluationCreate */
        SupplierEvaluationCreate: {
            /** Comment */
            comment?: string | null;
            /** Communication */
            communication: number;
            /** Expense Id */
            expense_id?: string | null;
            /** Quality */
            quality: number;
            /** Safety */
            safety: number;
            /**
             * Service Date
             * Format: date
             */
            service_date: string;
            /** Timeliness */
            timeliness: number;
            /** Value */
            value: number;
            /** Work Description */
            work_description: string;
            /**
             * Work Id
             * Format: uuid
             */
            work_id: string;
        };
        /** SupplierEvaluationUpdate */
        SupplierEvaluationUpdate: {
            /** Comment */
            comment?: string | null;
            /** Communication */
            communication: number;
            /** Expense Id */
            expense_id?: string | null;
            /** Quality */
            quality: number;
            /** Safety */
            safety: number;
            /**
             * Service Date
             * Format: date
             */
            service_date: string;
            /** Timeliness */
            timeliness: number;
            /** Value */
            value: number;
            /** Work Description */
            work_description: string;
            /**
             * Work Id
             * Format: uuid
             */
            work_id: string;
        };
        /** SupplierEvaluationVoid */
        SupplierEvaluationVoid: {
            /** Reason */
            reason: string;
        };
        /** SupplierSpecialtyCreate */
        SupplierSpecialtyCreate: {
            /** Name */
            name: string;
        };
        /** SupplierSpecialtyUpdate */
        SupplierSpecialtyUpdate: {
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Name */
            name: string;
        };
        /** SupplierUpdate */
        SupplierUpdate: {
            /** Address */
            address?: string | null;
            /** Contact Name */
            contact_name?: string | null;
            /** Coverage */
            coverage?: string | null;
            /** Email */
            email?: string | null;
            /** Legal Name */
            legal_name?: string | null;
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /** Phone */
            phone?: string | null;
            /** Postal Code */
            postal_code?: string | null;
            /** Specialty Ids */
            specialty_ids?: string[];
            /** Tax Id */
            tax_id?: string | null;
            /** Tax Regime */
            tax_regime?: string | null;
            /** Whatsapp */
            whatsapp?: string | null;
        };
        /** ToolDefinition */
        ToolDefinition: {
            /** Description */
            description: string;
            /** Mutates */
            mutates: boolean;
            /** Name */
            name: string;
            /**
             * Requires Confirmation
             * @default false
             */
            requires_confirmation: boolean;
            /** Roles */
            roles: components["schemas"]["Role"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WeeklyCloseCreate */
        WeeklyCloseCreate: {
            /** Iso Week */
            iso_week: number;
            /** Iso Year */
            iso_year: number;
            /**
             * Work Id
             * Format: uuid
             */
            work_id: string;
        };
        /** WeeklyReopen */
        WeeklyReopen: {
            /** Reason */
            reason: string;
        };
        /** WorkCreate */
        WorkCreate: {
            /** End Date */
            end_date?: string | null;
            /** Location */
            location?: string | null;
            /** Name */
            name: string;
            /** Start Date */
            start_date?: string | null;
        };
        /** WorkDelete */
        WorkDelete: {
            /** Confirmation Name */
            confirmation_name: string;
        };
        /** WorkSupplierAssignment */
        WorkSupplierAssignment: {
            /** Notes */
            notes?: string | null;
        };
        /** WorkUpdate */
        WorkUpdate: {
            /** End Date */
            end_date?: string | null;
            /** Location */
            location?: string | null;
            /** Name */
            name: string;
            /** Start Date */
            start_date?: string | null;
            /** State */
            state: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_dashboard_api_v1_dashboard_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_expenses_api_v1_expenses_get: {
        parameters: {
            query: {
                work_id: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_expense_api_v1_expenses_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_extract_receipt_api_v1_expenses_extract_receipt_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_post_extract_receipt_api_v1_expenses_extract_receipt_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptExtractionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_jev_chat_api_v1_expenses_jev_chat_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JevChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JevChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_expense_batch_review_api_v1_expenses_review_batch_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseBatchReview"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_expense_api_v1_expenses__expense_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_expense_cancel_api_v1_expenses__expense_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseCancel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_expense_receipt_api_v1_expenses__expense_id__receipt_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReceiptUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_expense_review_api_v1_expenses__expense_id__review_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseReview"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    hmac_probe_api_v1_hermes_hmac_probe_post: {
        parameters: {
            query?: never;
            header?: {
                "x-d89-key-id"?: string | null;
                "x-d89-timestamp"?: string | null;
                "x-d89-nonce"?: string | null;
                "x-d89-signature"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hermes_tools_api_v1_hermes_tools_get: {
        parameters: {
            query?: never;
            header?: {
                "x-d89-key-id"?: string | null;
                "x-d89-timestamp"?: string | null;
                "x-d89-nonce"?: string | null;
                "x-d89-signature"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolDefinition"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invoke_hermes_tool_api_v1_hermes_tools__tool_name__post: {
        parameters: {
            query?: never;
            header?: {
                "x-d89-actor-phone"?: string | null;
                "x-d89-key-id"?: string | null;
                "x-d89-timestamp"?: string | null;
                "x-d89-nonce"?: string | null;
                "x-d89-signature"?: string | null;
            };
            path: {
                tool_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_incomes_api_v1_incomes_get: {
        parameters: {
            query: {
                work_id: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_income_api_v1_incomes_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncomeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_neodata_import_api_v1_neodata_imports__import_id__confirm_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                import_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportConfirm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_neodata_preview_api_v1_neodata_imports__import_id__preview_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                import_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportPreviewUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_neodata_api_v1_neodata_preview_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_preview_neodata_api_v1_neodata_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_work_pdf_api_v1_reports_works__work_id__pdf_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                work_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_work_excel_api_v1_reports_works__work_id__xlsx_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                work_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subcontracts_api_v1_subcontracts_get: {
        parameters: {
            query: {
                work_id: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_subcontract_api_v1_subcontracts_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubcontractCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_subcontract_payment_api_v1_subcontracts__subcontract_id__payments_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                subcontract_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubcontractPaymentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_supplier_specialties_api_v1_supplier_specialties_get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_supplier_specialty_api_v1_supplier_specialties_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierSpecialtyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_supplier_specialty_api_v1_supplier_specialties__specialty_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                specialty_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierSpecialtyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_suppliers_api_v1_suppliers_get: {
        parameters: {
            query?: {
                q?: string | null;
                specialty_id?: string | null;
                min_rating?: number | string | null;
                active?: boolean | null;
                include_archived?: boolean;
                work_id?: string | null;
                sort?: string;
                page?: number;
                page_size?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_supplier_api_v1_suppliers_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_supplier_analytics_api_v1_suppliers_analytics_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_extract_csf_api_v1_suppliers_extract_csf_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_post_extract_csf_api_v1_suppliers_extract_csf_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsfExtractionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_supplier_detail_api_v1_suppliers__supplier_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                supplier_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_supplier_api_v1_suppliers__supplier_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                supplier_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierArchive"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_supplier_api_v1_suppliers__supplier_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                supplier_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_supplier_evaluation_api_v1_suppliers__supplier_id__evaluations_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                supplier_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierEvaluationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_supplier_evaluation_api_v1_suppliers__supplier_id__evaluations__evaluation_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                supplier_id: string;
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierEvaluationVoid"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_supplier_evaluation_api_v1_suppliers__supplier_id__evaluations__evaluation_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                supplier_id: string;
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierEvaluationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_supplier_restore_api_v1_suppliers__supplier_id__restore_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                supplier_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_supplier_work_api_v1_suppliers__supplier_id__works__work_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                supplier_id: string;
                work_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkSupplierAssignment"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_supplier_work_api_v1_suppliers__supplier_id__works__work_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                supplier_id: string;
                work_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_weekly_close_api_v1_weekly_closes_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeeklyCloseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_weekly_reopen_api_v1_weekly_closes__close_id__reopen_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                close_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeeklyReopen"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_works_api_v1_works_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_work_api_v1_works_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_work_detail_api_v1_works__work_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                work_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_work_api_v1_works__work_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                work_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkDelete"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_work_api_v1_works__work_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                work_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_work_catalog_api_v1_works__work_id__catalog_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                work_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_work_expenses_api_v1_works__work_id__expenses_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                state?: string | null;
                area_id?: string | null;
                q?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                work_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_work_overview_api_v1_works__work_id__overview_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                work_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_weekly_closes_api_v1_works__work_id__weekly_closes_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                work_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_weekly_close_preview_api_v1_works__work_id__weekly_closes_preview_get: {
        parameters: {
            query: {
                iso_year: number;
                iso_week: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                work_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
